-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 12:44:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mini_reg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini_reg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_reg` DEFAULT CHARACTER SET utf8 ;
USE `mini_reg` ;

-- -----------------------------------------------------
-- Table `mini_reg`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`students` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_reg`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`cards` (
  `id` INT NOT NULL,
  `card_no` VARCHAR(45) NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`id`, `students_id`),
  INDEX `fk_cards_students1_idx` (`students_id` ASC),
  CONSTRAINT `fk_cards_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `mini_reg`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_reg`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`courses` (
  `id` INT NOT NULL,
  `no` VARCHAR(6) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_reg`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`sections` (
  `id` INT NOT NULL,
  `lecture_no` VARCHAR(3) NULL,
  `laboratory_no` VARCHAR(3) NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`, `courses_id`),
  INDEX `fk_sections_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_sections_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `mini_reg`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_reg`.`section_enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`section_enrollments` (
  `sections_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`sections_id`, `students_id`),
  INDEX `fk_sections_has_students_students1_idx` (`students_id` ASC),
  INDEX `fk_sections_has_students_sections1_idx` (`sections_id` ASC),
  CONSTRAINT `fk_sections_has_students_sections1`
    FOREIGN KEY (`sections_id`)
    REFERENCES `mini_reg`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_has_students_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `mini_reg`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_reg`.`lecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_reg`.`lecturers` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
